# Generated by Django 3.2.12 on 2022-03-07 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Арендатор',
                'verbose_name_plural': 'Арендаторы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.PositiveBigIntegerField(verbose_name='ИНН')),
                ('ogrn', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ОГРН')),
                ('individual_entrepreneur', models.BooleanField(default=False, verbose_name='ИП')),
                ('individual', models.BooleanField(default=False, verbose_name='Физ. лицо')),
                ('egr', models.BooleanField(blank=True, default=False, null=True, verbose_name='Выписка ЕГР')),
                ('license', models.BooleanField(blank=True, default=False, null=True, verbose_name='Лицензия')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес имущества')),
                ('activity', models.CharField(max_length=500, verbose_name='Вид деятельности')),
                ('term', models.CharField(max_length=100, verbose_name='Срок аренды')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата подачи заявки')),
                ('fio', models.CharField(max_length=300, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('passport', models.PositiveBigIntegerField(verbose_name='Серия и номер паспорта')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.tenant', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
